version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoice_db
      MYSQL_USER: invoice_user
      MYSQL_PASSWORD: invoice_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  streamlit:
    build: .
    container_name: invoice_app
    depends_on:
      - mysql
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=mysql
      - DB_USER=invoice_user
      - DB_PASS=invoice_pass
      - DB_NAME=invoice_db
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes:
      - .:/app

  mcp:
    build: .
    container_name: mcp_server
    depends_on:
      mysql:
        condition: service_healthy
    command: ["uvicorn", "mcp_server:app", "--host", "0.0.0.0", "--port", "9000"]
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=mysql
      - DB_USER=invoice_user
      - DB_PASS=invoice_pass
      - DB_NAME=invoice_db
    volumes:
      - .:/app

volumes:
  mysql_data: